[variables]
PYTHON_VERSION = "3.12"
PYTHONUNBUFFERED = "1"
POETRY_VIRTUALENVS_IN_PROJECT = "true"
POETRY_NO_INTERACTION = "1"
WEB_CONCURRENCY = "2"
PLAYWRIGHT_BROWSERS_PATH = "/usr/lib/playwright"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"

[phases.setup]
nixPkgs = ["python312", "pipx", "file", "playwright-driver"]
cmds = ["pipx install poetry"]

[phases.install]
cmds = ["poetry install --no-root --only main"]

[start]
cmd = "poetry run uvicorn app.main:app --host 0.0.0.0 --port ${PORT} --proxy-headers --forwarded-allow-ips='*'"

