[variables]
PYTHON_VERSION = "3.12"
PYTHONUNBUFFERED = "1"
POETRY_VIRTUALENVS_IN_PROJECT = "true"
POETRY_NO_INTERACTION = "1"
WEB_CONCURRENCY = "2"
PLAYWRIGHT_BROWSERS_PATH = "/ms-playwright"

[phases.setup]
nixPkgs = [
  "python312","pipx","file","chromium",
  "freetype","fontconfig","nss","nspr","gtk3","pango","cups","libdrm","mesa","dbus",
  "xorg.libX11","xorg.libXcomposite","xorg.libXdamage","xorg.libXfixes","xorg.libXrandr","xorg.libxcb"
]
cmds = ["pipx install poetry"]

[phases.install]
cmds = ["poetry install --no-root --only main"]

[start]
cmd = "PLAYWRIGHT_BROWSERS_PATH=/ms-playwright poetry run python -m playwright install chromium && poetry run uvicorn app.main:app --host 0.0.0.0 --port ${PORT} --proxy-headers --forwarded-allow-ips='*'"

