[variables]
PYTHON_VERSION = "3.12"
PYTHONUNBUFFERED = "1"
POETRY_VIRTUALENVS_IN_PROJECT = "true"
POETRY_NO_INTERACTION = "1"
WEB_CONCURRENCY = "2"

[phases.setup]
nixPkgs = ["python312", "pipx"]
cmds = [
  "pipx install poetry"
]

[phases.install]
cmds = [
  "poetry install --no-root --only main"
]

[start]
cmd = "poetry run gunicorn app.main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:${PORT} --workers ${WEB_CONCURRENCY} --timeout 60"
